### PR TITLE
More updates

### PR DESCRIPTION
**Pull request by fgsch**
See individual commits for details.

### CODE REVIEW

**Comment by ejthurgo** [comment]
I know the validation implied otherwise, but the Service ID is not required for all operations.

**Comment by fgsch** [comment]
@ejthurgo Which operation does not need the service id?
You need the service Id to get the WAF id.

**Comment by LittleLadySunshine** [comment]
--help and --version

**Comment by fgsch** [comment]
You can run those commands without a service id although I wouldn't call them operations 😄

**Comment by LittleLadySunshine** [comment]
HAHAHAHA Agreed. Perhaps, how to operate :)

**Pull request merged**
