### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by zachsis**
added centos installation instructions for go newbies like me.

### CODE REVIEW

**Comment by fgsch** [comment]
Thanks for the PR. 

I'd prefer if we leave the go installation instructions out (or point users to https://golang.org/doc/install) rather than potentially adding it for every OS, and change CentOS to "Other OS".

**Comment by zachsis** [comment]
> Thanks for the PR.
> 
> I'd prefer if we leave the go installation instructions out (or point users to https://golang.org/doc/install) rather than potentially adding it for every OS, and change CentOS to "Other OS".

I'll make those changes, however since go isn't a widely adopted language yet, some customers may appreciate a TL;DR to get the tool up and running quickly. If I just remove the exports etc and change to 'Other OS' is that good? The `go get -v ...` option took a bit of digging and I think would help people install the tool + dependencies. I had a call with someone at Fastly the other day to go over WAF training, and during the session they requested we install this tool. Long story short I didn't get the tool installed in time during the session due to being new to `go`, so the session wasn't as beneficial as it should have been. Hoping to help future customers who aren't running MacOS

**Comment by fgsch** [comment]
> I'll make those changes, however since go isn't a widely adopted language yet, some customers may appreciate a TL;DR to get the tool up and running quickly. If I just remove the exports etc and change to 'Other OS' is that good?

Yes, that's exactly what I meant 👍 

> The go get -v ... option took a bit of digging and I think would help people install the tool + dependencies.

This is only needed if you want to build the tool.
We have binaries for different OS (including Linux) at https://github.com/fastly/waflyctl/releases. these don't have any requirements. This is mentioned in the README but we should probably make it more prominent.

**Comment by fgsch** [comment]
Could you rebase this PR as I've merged an outstanding PR just now? Sorry.

**Pull request merged**
